### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by craigcoles** [craigcoles/dem-movies#1]
#### Logic
- [ ] Possible to reduce number of API calls when requesting a random item from a genre?
#### Styling
- [ ] Style up genre menu
- [ ] Style up 404 page
#### Assets
- [ ] Do something with the backdrop images (File size, load times, if item does not have one)
- [ ] Update favicon
